kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redirector
  namespace: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: redirector
        image: cusspvz/redirect
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: HTTP_PORT
          value: '8080'
        - name: REDIRECT
          value: 'https://staging.eventyay.com'
      restartPolicy: Always
