apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-notls
  namespace: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.eventyay.com
    http:
      paths:
      - path: /
        backend:
          serviceName: https-redirector
          servicePort: 80
