apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-disk
  namespace: postgres
  labels:
    name: pg-data-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "staging-pg-data-disk"
    fsType: "ext4"
