apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.246.10
    path: "/data"
